/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 
package jservers;

import java.awt.print.PrinterException;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

*//**
 *
 * @author shreejal
 *//*
public class ServerFrame extends javax.swing.JFrame {

	*//**
	 * Creates new form ClientFrame
	 *//*

	DataInputStream dis = null;
	public SocketServer server;
	Socket socket;
	public Thread serverThread;

	public ServerFrame() throws IOException {
		initComponents();
		ta_server.setEditable(false);
	}

	*//**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 *//*
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		b_startServer = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		ta_server = new javax.swing.JTextArea();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		Cash_table = new javax.swing.JTable();
		b_print = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		b_startServer.setText("Start Server");
		b_startServer.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_startServerActionPerformed(evt);
			}
		});

		ta_server.setColumns(20);
		ta_server.setRows(5);
		jScrollPane1.setViewportView(ta_server);

		jButton1.setText("Send");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		Cash_table.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { 
						 }, new String[] {
						"TableNo", "Dish Name", "Quantity", "Order Status",
						"Unit Price" }) {
			Class[] types = new Class[] { java.lang.Integer.class,
					java.lang.String.class, java.lang.Integer.class,
					java.lang.String.class, java.lang.Integer.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jScrollPane2.setViewportView(Cash_table);

		b_print.setText("Print");
		b_print.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_printActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jScrollPane2)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														731, Short.MAX_VALUE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jTextField1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton1))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						b_startServer,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						121,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										b_print)
																								.addGap(61,
																										61,
																										61)))))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(b_startServer)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										123,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton1))
								.addGap(18, 18, 18)
								.addComponent(jScrollPane2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										158,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(b_print)
								.addContainerGap(239, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void b_startServerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b_startServerActionPerformed
		// TODO add your handling code here:\
		server = new SocketServer(this);
		b_startServer.setEnabled(false);
	}// GEN-LAST:event_b_startServerActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		
		
		// try {
		// // TODO add your handling code here:
		// String mssg = jTextField1.getText();
		// DataOutputStream dos = new
		// DataOutputStream(socket.getOutputStream());
		// dos.writeUTF(mssg);
		// // DataInputStream dis = new
		// DataInputStream(socket.getInputStream());
		// } catch (IOException ex) {
		// Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE, null,
		// ex);
		// }
	}// GEN-LAST:event_jButton1ActionPerformed

	private void b_printActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b_printActionPerformed
		// TODO add your handling code here:

		try {
			Boolean complete = Cash_table.print();

			if (complete) {
				JOptionPane.showMessageDialog(null, "Done Printing.");
			} else {
				JOptionPane.showMessageDialog(null, "Printing Canceled.");
			}
		} catch (PrinterException ex) {

			JOptionPane.showMessageDialog(null, ex);
			Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE,
					null, ex);
		}
	}// GEN-LAST:event_b_printActionPerformed

	public void RetryStart(int port) {
		if (server != null) {
			server.stop();
		}
		server = new SocketServer(this, port);
	}

	*//**
	 * @param args
	 *            the command line arguments
	 *//*
	public static void main(String args[]) {
		 Set the Nimbus look and feel 
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ServerFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ServerFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ServerFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ServerFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		 Create and display the form 
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new ServerFrame().setVisible(true);
				} catch (IOException ex) {
					Logger.getLogger(ServerFrame.class.getName()).log(
							Level.SEVERE, null, ex);
				}
			}
		});
		// DataInputStream dis = new DataInputStream(Socket.getInputStream());
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JTable Cash_table;
	private javax.swing.JButton b_print;
	private javax.swing.JButton b_startServer;
	private javax.swing.JButton jButton1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextField jTextField1;
	public javax.swing.JTextArea ta_server;
	// End of variables declaration//GEN-END:variables
}*/